FROM benjum/xgb-week5:arm64
# or amd64 as appropriate

USER root

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends \
  graphviz \
  patch \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*


USER $NB_UID
